### ISSUE TITLE
FPC 3.2 includes  "stock" generics

### ISSUE THREAD

**Issue by the-Arioch** [jackdp/JPPack#2]
Dependency upon Sparta generics have to be removed from Lazarus package, or it would not compile.

[jplib_sparta_patch.ZIP](https://github.com/jackdp/JPPack/files/7857771/jplib_sparta_patch.ZIP)

https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39539

**Comment by jackdp** [comment]
Thank you.
Fixed.
